apiVersion: v1
kind: Pod
metadata:
  name: app-nginx-pod
spec:
  containers:
  - name: app-nginx-container
    image: nginx
    env:
      - name: SERVER_URL
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: SERVER_URL
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: app-pv
      - mountPath: /etc/test
        name: secret-volume
  volumes:
    - name: app-pv
      persistentVolumeClaim:
        claimName: app-pvc
    - name: secret-volume
      secret:
        secretName: app-secret