trigger:
  branches:
    include:
    - main
  paths:
    exclude:
      - Pipelines
      - Terraform
      - Troubleshooting
      - README.md

pool:
  vmImage: 'windows-latest'

variables:
- group: Terraform
- group: sql-credentials
- name: skipBuildStage
  value: false
- name: skipTerraformStage
  value: false
- name: ServicePrincipal
  value: 'Azure sub' # Change to the name of your Service Connection
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'

stages:
- stage: Build
  condition: eq(variables.skipBuildStage, false)
  displayName: 'Build Stage'
  jobs:
    - job: Build
      displayName: 'Build Job'
      steps:
      - template: templates/build-pipeline.yml

- stage: Terraform
  condition: eq(variables.skipTerraformStage, false)
  displayName: 'Terraform Stage'
  jobs:
    - job: Infrastructure
      displayName: 'Provisioning Infrastructure'
      steps:
      - template: templates/terraform-pipeline.yml

- stage: Deployment
  displayName: 'Deployment Stage'
  dependsOn: Terraform 
  jobs:
    - job: Deploy
      displayName: 'App Deployment Job'
      variables:
        sqlServerName: $[ stageDependencies.Terraform.Infrastructure.outputs['Results.SQL_SERVER_NAME'] ]
        rgpName: $[ stageDependencies.Terraform.Infrastructure.outputs['Results.RGP_NAME'] ]
        appName: $[ stageDependencies.Terraform.Infrastructure.outputs['Results.APP_NAME'] ]
      steps:
      - template: templates/deploy-pipeline.yml
